<Project Sdk="Microsoft.NET.Sdk.BlazorWebAssembly">

	<ItemGroup>
		<Compile Remove="wwwroot\bootstrap-5.3.3-dist\**" />
		<Content Remove="wwwroot\bootstrap-5.3.3-dist\**" />
		<EmbeddedResource Remove="wwwroot\bootstrap-5.3.3-dist\**" />
		<None Remove="wwwroot\bootstrap-5.3.3-dist\**" />
	</ItemGroup>

	<ItemGroup>
		<Content Remove="Components\Login.razor" />
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="Microsoft.AspNetCore.Components.QuickGrid" />
		<PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly"  />
		<PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly.Authentication" />
		<PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly.DevServer" PrivateAssets="all" />
		<PackageReference Include="Microsoft.Extensions.Http" />
		<PackageReference Include="Syncfusion.Blazor.Buttons" />
		<PackageReference Include="Syncfusion.Blazor.Calendars" />
		<PackageReference Include="Syncfusion.Blazor.Charts" />
		<PackageReference Include="Syncfusion.Blazor.Navigations" />
		<PackageReference Include="Syncfusion.Blazor.Popups"/>
		<PackageReference Include="Syncfusion.Blazor.Themes"/>
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\BaseLibrary\BaseLibrary.csproj" />
	</ItemGroup>

	<ItemGroup>
		<UpToDateCheckInput Remove="Components\Login.razor" />
	</ItemGroup>

	<ItemGroup>
		<_ContentIncludedByDefault Remove="Components\Login.razor" />
		<_ContentIncludedByDefault Remove="Pages\Dashboard.razor" />
		<_ContentIncludedByDefault Remove="Pages\Logout.razor" />
		<_ContentIncludedByDefault Remove="staticwebapp.config.json" />
	</ItemGroup>

	<ItemGroup>
		<None Include="Pages\Login.razor" />
	</ItemGroup>

	<ItemGroup>
		<UpToDateCheckInput Remove="Pages\Dashboard.razor" />
	</ItemGroup>

	<ItemGroup>
		<UpToDateCheckInput Remove="Pages\Logout.razor" />
	</ItemGroup>

</Project>
